name: Node.js Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 'Create server env file'
        working-directory: ./server
        run: |
          echo "${{ secrets.DEV_SERVER_ENV }}" >> .env
          cat .env

      - name: 'Create client env file'
        working-directory: ./client
        run: |
          echo "${{ secrets.DEV_CLIENT_ENV }}" >> .env
          cat .env
