name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: check modified files
      uses: Stockopedia/action-get-changed-files@v2.0.0
      id: get_changed
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        foldersOnly: true
        format: json

    - name: Echo
      id: echo_step
      run: echo ${{ steps.get_changed.outputs.changed }}

  run_if_client:
    name: Run if client detected
    needs: check
    if: contains(needs.check.outputs.run_job, 'client')
    runs-on: ubuntu-latest
    steps:
      - name: Your Job Steps
        run: |
          echo "Client detected"
