name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for changes in the client directory
      id: check-client-changes
      run: |
        git diff --exit-code --quiet HEAD^ HEAD client || exit 0

    - name: Build and deploy client
      if: steps.check-client-changes.outputs.result == 'true'
      run: |
        # Add your build and deploy commands for the client here

    - name: Build and deploy server
      run: |
        # Add your build and deploy commands for the server here
