name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check files
    outputs:
      output1: ${{ steps.get_changed.outputs.output }}
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: check modified files
      uses: Stockopedia/action-get-changed-files@v2.0.0
      id: get_changed
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        foldersOnly: true
        format: csv

    - name: Echov1
      id: echo_stepv1
      run: echo ${{ steps.get_changed.outputs.changed }}

    - name: Echov2
      id: echo_stepv2
      run: echo "output=${{ steps.get_changed.outputs.changed }}" >> "$GITHUB_OUTPUT"

  check_output:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - env:
          RUN_JOB: ${{ needs.check.outputs.output1 }}
        run: echo $RUN_JOB

  # run_if_client:
  #   name: Run if client detected
  #   needs: check
  #   if: contains(needs.check.outputs.run_job, 'client')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Your Job Steps
  #       run: |
  #         echo "Client detected"
