name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for changes in the client directory
      id: check-client-changes
      run: |
        CLIENT_CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} client)
        if [ -z "$CLIENT_CHANGES" ]; then
          echo "No changes in the client directory. Exiting workflow."
          exit 0
        else
          echo "Changes detected in the client directory. Continuing with the workflow."
        fi

    - name: Build and deploy client
      if: steps.check-client-changes.outputs.result == 'true'
      run: |
        # Add your build and deploy commands for the client here

    - name: Build and deploy server
      run: |
        # Add your build and deploy commands for the server here
