name: OtherTests

on:
  push:
    branches:
      - main

jobs:
    job1:
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        output1: ${{ steps.step1.outputs.test }}
        output2: ${{ steps.step2.outputs.test }}
        output5: ${{ steps.step5.outputs.test }}
      steps:
        - id: step1
          run: echo "test=hello" >> "$GITHUB_OUTPUT"
        - id: step2
          run: echo "test=world" >> "$GITHUB_OUTPUT"
        - id: step3
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
        - id: step4
          uses: Stockopedia/action-get-changed-files@v2.0.0
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            foldersOnly: true
            format: csv
        - id: step5
          run: |
            echo "test=${{ steps.step4.outputs.changed }}" >> "$GITHUB_OUTPUT"
        - id: step6
          run: echo "${{ steps.step4.outputs.changed }}"
    job2:
      runs-on: ubuntu-latest
      needs: job1
      # if need1 output5 contains .github
      if: contains(needs.job1.outputs.output5, 'client')
      steps:
        - env:
            OUTPUT1: ${{needs.job1.outputs.output1}}
            OUTPUT2: ${{needs.job1.outputs.output2}}
            OUTPUT3: ${{needs.job1.outputs.output3}}
            OUTPUT4: ${{needs.job1.outputs.output4}}
            OUTPUT5: ${{needs.job1.outputs.output5}}
          run: echo "$OUTPUT1 $OUTPUT2 $OUTPUT5"
